---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-symlinks
      - id: check-yaml
      - id: check-json
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
        name: Fix requirements*.txt
        files: ^requirements.*\.txt$
      - id: trailing-whitespace
