name: Test Pyodide Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-pyodide:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "yarn"
        cache-dependency-path: ./yarn.lock

    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile --dev
    
    - name: Start HTTP server
      run: |
        yarn http-server . -p 8080 &
        sleep 5  # Give the server time to start

    - name: Run Pyodide tests
      run: |
        yarn test
    
    - name: Archive test artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-screenshots
        path: tests/screenshots
        retention-days: 5
